apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
  labels:
    app: node-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-service
  template:
    metadata:
      labels:
        app: node-service
    spec:
      containers:
      - name: node-service
        image: IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: node-service-config
        - secretRef:
            name: node-service-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: api/health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: api/health
            port: 4000
          initialDelaySeconds: 20
          periodSeconds: 10
