apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-service
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: node-service
