apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: python-service
