version: '3.8'

services:
  # Node.js service
  node-service:
    build: ./node-service
    ports:
      - "4000:4000"
    environment:
      - JAVA_SERVICE_URL=http://java-service:8080
      - PYTHON_SERVICE_URL=http://python-service:5000
    depends_on:
      - db
    networks:
      - microservices-network

  # Java service
  java-service:
    build: ./java-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todoappdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
    depends_on:
      - db
    networks:
      - microservices-network

  # Python service
  python-service:
    build: ./python-service
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=todoappdb
    depends_on:
      - db
    networks:
      - microservices-network

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_NODE_SERVICE_URL=http://localhost:4000
      - REACT_APP_JAVA_SERVICE_URL=http://localhost:8080
      - REACT_APP_PYTHON_SERVICE_URL=http://localhost:5000
    depends_on:
      - node-service
      - java-service
      - python-service
    networks:
      - microservices-network

  # Database
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todoappdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql-data:
