apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # root (base64 encoded)
  MYSQL_USER: YWRtaW4=  # admin (base64 encoded)
  MYSQL_PASSWORD: YWRtaW4xMjM=  # admin123 (base64 encoded)
