apiVersion: v1
kind: Secret
metadata:
  name: java-service-secret
type: Opaque
data:
  DB_HOST: bWljcm9zZXJ2aWNlcy1kYi5jdmdneWE2a2cxcjcudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t  # microservices-db.cvggya6kg1r7.us-east-1.rds.amazonaws.com (base64 encoded)
  DB_PASSWORD: YWRtaW4xMjM=  # admin123 (base64 encoded)
