apiVersion: v1
kind: Service
metadata:
  name: java-service
  labels:
    app: java-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: java-service
