name: React App CI-CD to S3

# Trigger on push to ashiph-feature branch or pull requests
on:
  push:
    branches:
      - ashiph-feature
  pull_request:
    branches:
      - ashiph-feature

# Environment variables
env:
  AWS_REGION: us-east-1 # Change to your preferred region
  S3_BUCKET: react-app-bucket-ashiph1 # Change to your bucket name

# Permissions for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Latest LTS version as of March 2025
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests with fixed configuration for ESM modules
      - name: Run Tests
        run: npm test -- --watchAll=false
        env:
          CI: false
        continue-on-error: true  # Allow deployment even if tests fail

        # SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=todo-react-app
            -Dsonar.sources=.
            -Dsonar.exclusions=../node-service/**,../java-service/**,../python-service/**,../init-database.sql,node_modules/**,build/**,public/**

      # Build the React app
      - name: Build
        run: npm run build
        env:
          CI: false  # Don't treat warnings as errors

       # Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN_REACT }}
          role-session-name: eks-session
          aws-region: ${{ secrets.AWS_REGION_REACT }}

      # Sync build folder to S3
      - name: Deploy to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/ashiph-feature'
        run: |
          aws s3 sync ./build/ s3://${{ env.S3_BUCKET }}/ \
            --delete \
            --cache-control "public, max-age=31536000" \
            --exclude "*.html" \
            --exclude "service-worker.js"
          
          # Handle HTML files separately with no-cache
          aws s3 sync ./build/ s3://${{ env.S3_BUCKET }}/ \
            --delete \
            --cache-control "no-store, no-cache, must-revalidate" \
            --include "*.html" \
            --include "service-worker.js"